### ISSUE TITLE
[HttpError: Requires authentication] {   message: 'Requires authentication',

### ISSUE THREAD

**Issue by arman66** [boobadiallo/project-creation-automation#1]
The script no longer works, been using it for a while but now I get a authentication error, statusCode: 401

**Comment by ghost** [comment]
Thanks for bringing this to my attention, I haven't used this command in a little while..

It turns out Github has changed their APIs and deprecated the use of *password* to authenticate (see [this issue](https://github.com/pksunkara/octonode/issues/338) on the Octonode repo).

Here's what I did to fix:
- I created a personal access token on Github (see Github docs [link](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token))
- I replaced the GITHUB_PASSWORD value in .env with the newly generated token
